spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog-rest-api
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#  jackson:
#    property-naming-strategy: SNAKE_CASE
springdoc:
  swagger-ui:
    path: /swagger

# App properties
app:
  base-uri: http://localhost:8080/
  name: my-blog
  jwt-secret: 413F4428472B4B6250645367566B5970337336763979244226452948404D6351
#  jwt-expiration-ms: 60000 #1 min
#  jwt-refresh-expiration-ms: 120000 #2 min
  jwt-expiration-ms: 3600000
  jwt-refresh-expiration-ms: 86400000
